//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let segue = segue()
  let reuseIdentifier = reuseIdentifier()

  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 42 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: A reset email has been sent to 
      ///
      /// Key: A reset email has been sent to
      ///
      /// Locales: en
      var aResetEmailHasBeenSentTo: RswiftResources.StringResource { .init(key: "A reset email has been sent to", tableName: "Localizable", source: source, developmentValue: "A reset email has been sent to ", comment: nil) }

      /// en translation: Addis Ababa
      ///
      /// Key: Addis Ababa
      ///
      /// Locales: en
      var addisAbaba: RswiftResources.StringResource { .init(key: "Addis Ababa", tableName: "Localizable", source: source, developmentValue: "Addis Ababa", comment: nil) }

      /// en translation: Couldn't Sign in
      ///
      /// Key: Couldn'tSignin
      ///
      /// Locales: en
      var couldnTSignin: RswiftResources.StringResource { .init(key: "Couldn'tSignin", tableName: "Localizable", source: source, developmentValue: "Couldn't Sign in", comment: nil) }

      /// en translation: Couldn't Sign up
      ///
      /// Key: Couldn'tSignup
      ///
      /// Locales: en
      var couldnTSignup: RswiftResources.StringResource { .init(key: "Couldn'tSignup", tableName: "Localizable", source: source, developmentValue: "Couldn't Sign up", comment: nil) }

      /// en translation: Danish
      ///
      /// Key: Danish
      ///
      /// Locales: en
      var danish: RswiftResources.StringResource { .init(key: "Danish", tableName: "Localizable", source: source, developmentValue: "Danish", comment: nil) }

      /// en translation: Dansk
      ///
      /// Key: Dansk
      ///
      /// Locales: en
      var dansk: RswiftResources.StringResource { .init(key: "Dansk", tableName: "Localizable", source: source, developmentValue: "Dansk", comment: nil) }

      /// en translation: Done
      ///
      /// Key: Done
      ///
      /// Locales: en
      var done: RswiftResources.StringResource { .init(key: "Done", tableName: "Localizable", source: source, developmentValue: "Done", comment: nil) }

      /// en translation: Dutch
      ///
      /// Key: Dutch
      ///
      /// Locales: en
      var dutch: RswiftResources.StringResource { .init(key: "Dutch", tableName: "Localizable", source: source, developmentValue: "Dutch", comment: nil) }

      /// en translation: 
      ///
      /// Key: Empty
      ///
      /// Locales: en
      var empty: RswiftResources.StringResource { .init(key: "Empty", tableName: "Localizable", source: source, developmentValue: "", comment: nil) }

      /// en translation: English(Australia)
      ///
      /// Key: English(Australia)
      ///
      /// Locales: en
      var englishAustralia: RswiftResources.StringResource { .init(key: "English(Australia)", tableName: "Localizable", source: source, developmentValue: "English(Australia)", comment: nil) }

      /// en translation: English(Canada)
      ///
      /// Key: English(Canada)
      ///
      /// Locales: en
      var englishCanada: RswiftResources.StringResource { .init(key: "English(Canada)", tableName: "Localizable", source: source, developmentValue: "English(Canada)", comment: nil) }

      /// en translation: English(United States)
      ///
      /// Key: English(United States)
      ///
      /// Locales: en
      var englishUnitedStates: RswiftResources.StringResource { .init(key: "English(United States)", tableName: "Localizable", source: source, developmentValue: "English(United States)", comment: nil) }

      /// en translation: Error
      ///
      /// Key: Error
      ///
      /// Locales: en
      var error: RswiftResources.StringResource { .init(key: "Error", tableName: "Localizable", source: source, developmentValue: "Error", comment: nil) }

      /// en translation: Frankfurt
      ///
      /// Key: Frankfurt
      ///
      /// Locales: en
      var frankfurt: RswiftResources.StringResource { .init(key: "Frankfurt", tableName: "Localizable", source: source, developmentValue: "Frankfurt", comment: nil) }

      /// en translation: Heathrow
      ///
      /// Key: Heathrow
      ///
      /// Locales: en
      var heathrow: RswiftResources.StringResource { .init(key: "Heathrow", tableName: "Localizable", source: source, developmentValue: "Heathrow", comment: nil) }

      /// en translation: HomeViewController
      ///
      /// Key: HomeViewController
      ///
      /// Locales: en
      var homeViewController: RswiftResources.StringResource { .init(key: "HomeViewController", tableName: "Localizable", source: source, developmentValue: "HomeViewController", comment: nil) }

      /// en translation: Hong Kong
      ///
      /// Key: Hong Kong
      ///
      /// Locales: en
      var hongKong: RswiftResources.StringResource { .init(key: "Hong Kong", tableName: "Localizable", source: source, developmentValue: "Hong Kong", comment: nil) }

      /// en translation: Italian
      ///
      /// Key: Italian
      ///
      /// Locales: en
      var italian: RswiftResources.StringResource { .init(key: "Italian", tableName: "Localizable", source: source, developmentValue: "Italian", comment: nil) }

      /// en translation: Italy
      ///
      /// Key: Italy
      ///
      /// Locales: en
      var italy: RswiftResources.StringResource { .init(key: "Italy", tableName: "Localizable", source: source, developmentValue: "Italy", comment: nil) }

      /// en translation: LanguageCell
      ///
      /// Key: LanguageCell
      ///
      /// Locales: en
      var languageCell: RswiftResources.StringResource { .init(key: "LanguageCell", tableName: "Localizable", source: source, developmentValue: "LanguageCell", comment: nil) }

      /// en translation: Netherlands
      ///
      /// Key: Netherlands
      ///
      /// Locales: en
      var netherlands: RswiftResources.StringResource { .init(key: "Netherlands", tableName: "Localizable", source: source, developmentValue: "Netherlands", comment: nil) }

      /// en translation: New Delhi
      ///
      /// Key: New Delhi
      ///
      /// Locales: en
      var newDelhi: RswiftResources.StringResource { .init(key: "New Delhi", tableName: "Localizable", source: source, developmentValue: "New Delhi", comment: nil) }

      /// en translation: OK
      ///
      /// Key: OK
      ///
      /// Locales: en
      var oK: RswiftResources.StringResource { .init(key: "OK", tableName: "Localizable", source: source, developmentValue: "OK", comment: nil) }

      /// en translation: Please try again
      ///
      /// Key: Please try again
      ///
      /// Locales: en
      var pleaseTryAgain: RswiftResources.StringResource { .init(key: "Please try again", tableName: "Localizable", source: source, developmentValue: "Please try again", comment: nil) }

      /// en translation: Success
      ///
      /// Key: Success
      ///
      /// Locales: en
      var success: RswiftResources.StringResource { .init(key: "Success", tableName: "Localizable", source: source, developmentValue: "Success", comment: nil) }

      /// en translation: Wroclow
      ///
      /// Key: Wroclow
      ///
      /// Locales: en
      var wroclow: RswiftResources.StringResource { .init(key: "Wroclow", tableName: "Localizable", source: source, developmentValue: "Wroclow", comment: nil) }

      /// en translation: Wrong Code
      ///
      /// Key: Wrong Code
      ///
      /// Locales: en
      var wrongCode: RswiftResources.StringResource { .init(key: "Wrong Code", tableName: "Localizable", source: source, developmentValue: "Wrong Code", comment: nil) }

      /// en translation: backToHomepageSegue
      ///
      /// Key: backToHomepageSegue
      ///
      /// Locales: en
      var backToHomepageSegue: RswiftResources.StringResource { .init(key: "backToHomepageSegue", tableName: "Localizable", source: source, developmentValue: "backToHomepageSegue", comment: nil) }

      /// en translation: backToLoginSegue
      ///
      /// Key: backToLoginSegue
      ///
      /// Locales: en
      var backToLoginSegue: RswiftResources.StringResource { .init(key: "backToLoginSegue", tableName: "Localizable", source: source, developmentValue: "backToLoginSegue", comment: nil) }

      /// en translation: backToSettingsSegue
      ///
      /// Key: backToSettingsSegue
      ///
      /// Locales: en
      var backToSettingsSegue: RswiftResources.StringResource { .init(key: "backToSettingsSegue", tableName: "Localizable", source: source, developmentValue: "backToSettingsSegue", comment: nil) }

      /// en translation: backToVerficationSegue
      ///
      /// Key: backToVerficationSegue
      ///
      /// Locales: en
      var backToVerficationSegue: RswiftResources.StringResource { .init(key: "backToVerficationSegue", tableName: "Localizable", source: source, developmentValue: "backToVerficationSegue", comment: nil) }

      /// en translation: email
      ///
      /// Key: email
      ///
      /// Locales: en
      var email: RswiftResources.StringResource { .init(key: "email", tableName: "Localizable", source: source, developmentValue: "email", comment: nil) }

      /// en translation: goBackToForgotPass
      ///
      /// Key: goBackToForgotPass
      ///
      /// Locales: en
      var goBackToForgotPass: RswiftResources.StringResource { .init(key: "goBackToForgotPass", tableName: "Localizable", source: source, developmentValue: "goBackToForgotPass", comment: nil) }

      /// en translation: goToCodeSegue
      ///
      /// Key: goToCodeSegue
      ///
      /// Locales: en
      var goToCodeSegue: RswiftResources.StringResource { .init(key: "goToCodeSegue", tableName: "Localizable", source: source, developmentValue: "goToCodeSegue", comment: nil) }

      /// en translation: goToLoginAfterNewPass
      ///
      /// Key: goToLoginAfterNewPass
      ///
      /// Locales: en
      var goToLoginAfterNewPass: RswiftResources.StringResource { .init(key: "goToLoginAfterNewPass", tableName: "Localizable", source: source, developmentValue: "goToLoginAfterNewPass", comment: nil) }

      /// en translation: goToNewPassword
      ///
      /// Key: goToNewPassword
      ///
      /// Locales: en
      var goToNewPassword: RswiftResources.StringResource { .init(key: "goToNewPassword", tableName: "Localizable", source: source, developmentValue: "goToNewPassword", comment: nil) }

      /// en translation: showCreateAccountPage
      ///
      /// Key: showCreateAccountPage
      ///
      /// Locales: en
      var showCreateAccountPage: RswiftResources.StringResource { .init(key: "showCreateAccountPage", tableName: "Localizable", source: source, developmentValue: "showCreateAccountPage", comment: nil) }

      /// en translation: showForgotPasswordPage
      ///
      /// Key: showForgotPasswordPage
      ///
      /// Locales: en
      var showForgotPasswordPage: RswiftResources.StringResource { .init(key: "showForgotPasswordPage", tableName: "Localizable", source: source, developmentValue: "showForgotPasswordPage", comment: nil) }

      /// en translation: showLanguagesPage
      ///
      /// Key: showLanguagesPage
      ///
      /// Locales: en
      var showLanguagesPage: RswiftResources.StringResource { .init(key: "showLanguagesPage", tableName: "Localizable", source: source, developmentValue: "showLanguagesPage", comment: nil) }

      /// en translation: showLoginPage
      ///
      /// Key: showLoginPage
      ///
      /// Locales: en
      var showLoginPage: RswiftResources.StringResource { .init(key: "showLoginPage", tableName: "Localizable", source: source, developmentValue: "showLoginPage", comment: nil) }

      /// en translation: showSettingsPage
      ///
      /// Key: showSettingsPage
      ///
      /// Locales: en
      var showSettingsPage: RswiftResources.StringResource { .init(key: "showSettingsPage", tableName: "Localizable", source: source, developmentValue: "showSettingsPage", comment: nil) }

      /// en translation: signOutSegue
      ///
      /// Key: signOutSegue
      ///
      /// Locales: en
      var signOutSegue: RswiftResources.StringResource { .init(key: "signOutSegue", tableName: "Localizable", source: source, developmentValue: "signOutSegue", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 6 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `Color`.
    var color: RswiftResources.ColorResource { .init(name: "Color", path: [], bundle: bundle) }

    /// Color `DisabledButton`.
    var disabledButton: RswiftResources.ColorResource { .init(name: "DisabledButton", path: [], bundle: bundle) }

    /// Color `DisabledTitleColor`.
    var disabledTitleColor: RswiftResources.ColorResource { .init(name: "DisabledTitleColor", path: [], bundle: bundle) }

    /// Color `EnabledButton`.
    var enabledButton: RswiftResources.ColorResource { .init(name: "EnabledButton", path: [], bundle: bundle) }

    /// Color `borderColorBlue`.
    var borderColorBlue: RswiftResources.ColorResource { .init(name: "borderColorBlue", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 12 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Line1`.
    var line1: RswiftResources.ImageResource { .init(name: "Line1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `MenuScreen`.
    var menuScreen: RswiftResources.ImageResource { .init(name: "MenuScreen", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Rectangle`.
    var rectangle: RswiftResources.ImageResource { .init(name: "Rectangle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Rectangle_all`.
    var rectangle_all: RswiftResources.ImageResource { .init(name: "Rectangle_all", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Rectangle_big`.
    var rectangle_big: RswiftResources.ImageResource { .init(name: "Rectangle_big", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Rectangle_suggested`.
    var rectangle_suggested: RswiftResources.ImageResource { .init(name: "Rectangle_suggested", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Rectangle_white`.
    var rectangle_white: RswiftResources.ImageResource { .init(name: "Rectangle_white", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Start`.
    var start: RswiftResources.ImageResource { .init(name: "Start", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `button`.
    var button: RswiftResources.ImageResource { .init(name: "button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `button_on`.
    var button_on: RswiftResources.ImageResource { .init(name: "button_on", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cb`.
    var cb: RswiftResources.ImageResource { .init(name: "cb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabler-icon-message-language`.
    var tablerIconMessageLanguage: RswiftResources.ImageResource { .init(name: "tabler-icon-message-language", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Main" }
          }
        }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.segue` struct is generated, and contains static references to 9 view controllers.
  struct segue {
    let forgotPasswordViewController = forgotPasswordViewController()
    let homeViewController = homeViewController()
    let languageViewController = languageViewController()
    let loginViewController = loginViewController()
    let newPasswordViewController = newPasswordViewController()
    let registrationViewController = registrationViewController()
    let settingsViewController = settingsViewController()
    let startViewController = startViewController()
    let verificationCodeViewController = verificationCodeViewController()

    /// This struct is generated for `ForgotPasswordViewController`, and contains static references to 2 segues.
    struct forgotPasswordViewController {

      /// Segue identifier `backToLoginSegue`.
      var backToLoginSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, ForgotPasswordViewController, LoginViewController> { .init(identifier: "backToLoginSegue") }

      /// Segue identifier `goToCodeSegue`.
      var goToCodeSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, ForgotPasswordViewController, VerificationCodeViewController> { .init(identifier: "goToCodeSegue") }
    }

    /// This struct is generated for `HomeViewController`, and contains static references to 1 segues.
    struct homeViewController {

      /// Segue identifier `showSettingsPage`.
      var showSettingsPage: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, HomeViewController, SettingsViewController> { .init(identifier: "showSettingsPage") }
    }

    /// This struct is generated for `LanguageViewController`, and contains static references to 1 segues.
    struct languageViewController {

      /// Segue identifier `backToSettingsSegue`.
      var backToSettingsSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, LanguageViewController, SettingsViewController> { .init(identifier: "backToSettingsSegue") }
    }

    /// This struct is generated for `LoginViewController`, and contains static references to 3 segues.
    struct loginViewController {

      /// Segue identifier `HomeViewController`.
      var homeViewController: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, LoginViewController, HomeViewController> { .init(identifier: "HomeViewController") }

      /// Segue identifier `showCreateAccountPage`.
      var showCreateAccountPage: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, LoginViewController, RegistrationViewController> { .init(identifier: "showCreateAccountPage") }

      /// Segue identifier `showForgotPasswordPage`.
      var showForgotPasswordPage: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, LoginViewController, ForgotPasswordViewController> { .init(identifier: "showForgotPasswordPage") }
    }

    /// This struct is generated for `NewPasswordViewController`, and contains static references to 2 segues.
    struct newPasswordViewController {

      /// Segue identifier `backToVerficationSegue`.
      var backToVerficationSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, NewPasswordViewController, VerificationCodeViewController> { .init(identifier: "backToVerficationSegue") }

      /// Segue identifier `goToLoginAfterNewPass`.
      var goToLoginAfterNewPass: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, NewPasswordViewController, LoginViewController> { .init(identifier: "goToLoginAfterNewPass") }
    }

    /// This struct is generated for `RegistrationViewController`, and contains static references to 2 segues.
    struct registrationViewController {

      /// Segue identifier `HomeViewController`.
      var homeViewController: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, RegistrationViewController, HomeViewController> { .init(identifier: "HomeViewController") }

      /// Segue identifier `showLoginPage`.
      var showLoginPage: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, RegistrationViewController, LoginViewController> { .init(identifier: "showLoginPage") }
    }

    /// This struct is generated for `SettingsViewController`, and contains static references to 3 segues.
    struct settingsViewController {

      /// Segue identifier `backToHomepageSegue`.
      var backToHomepageSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, SettingsViewController, HomeViewController> { .init(identifier: "backToHomepageSegue") }

      /// Segue identifier `showLanguagesPage`.
      var showLanguagesPage: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, SettingsViewController, LanguageViewController> { .init(identifier: "showLanguagesPage") }

      /// Segue identifier `signOutSegue`.
      var signOutSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, SettingsViewController, StartViewController> { .init(identifier: "signOutSegue") }
    }

    /// This struct is generated for `StartViewController`, and contains static references to 2 segues.
    struct startViewController {

      /// Segue identifier `ShowLoginPageSegue`.
      var showLoginPageSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, StartViewController, LoginViewController> { .init(identifier: "ShowLoginPageSegue") }

      /// Segue identifier `ShowRegistrationPageSegue`.
      var showRegistrationPageSegue: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, StartViewController, RegistrationViewController> { .init(identifier: "ShowRegistrationPageSegue") }
    }

    /// This struct is generated for `VerificationCodeViewController`, and contains static references to 2 segues.
    struct verificationCodeViewController {

      /// Segue identifier `goBackToForgotPass`.
      var goBackToForgotPass: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, VerificationCodeViewController, ForgotPasswordViewController> { .init(identifier: "goBackToForgotPass") }

      /// Segue identifier `goToNewPassword`.
      var goToNewPassword: RswiftResources.SegueIdentifier<UIKit.UIStoryboardSegue, VerificationCodeViewController, NewPasswordViewController> { .init(identifier: "goToNewPassword") }
    }
  }

  /// This `_R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {

    /// Reuse identifier `LanguageCell`.
    let languageCell: RswiftResources.ReuseIdentifier<UIKit.UITableViewCell> = .init(identifier: "LanguageCell")
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "Start", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Start' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = StartViewController

      let bundle: Foundation.Bundle

      let name = "Main"

      var forgotPasswordViewController: RswiftResources.StoryboardViewControllerIdentifier<ForgotPasswordViewController> { .init(identifier: "ForgotPasswordViewController", storyboard: name, bundle: bundle) }
      var homeViewController: RswiftResources.StoryboardViewControllerIdentifier<HomeViewController> { .init(identifier: "HomeViewController", storyboard: name, bundle: bundle) }
      var languageViewController: RswiftResources.StoryboardViewControllerIdentifier<LanguageViewController> { .init(identifier: "LanguageViewController", storyboard: name, bundle: bundle) }
      var loginViewController: RswiftResources.StoryboardViewControllerIdentifier<LoginViewController> { .init(identifier: "LoginViewController", storyboard: name, bundle: bundle) }
      var newPasswordViewController: RswiftResources.StoryboardViewControllerIdentifier<NewPasswordViewController> { .init(identifier: "NewPasswordViewController", storyboard: name, bundle: bundle) }
      var registrationViewController: RswiftResources.StoryboardViewControllerIdentifier<RegistrationViewController> { .init(identifier: "RegistrationViewController", storyboard: name, bundle: bundle) }
      var settingsViewController: RswiftResources.StoryboardViewControllerIdentifier<SettingsViewController> { .init(identifier: "SettingsViewController", storyboard: name, bundle: bundle) }
      var startViewController: RswiftResources.StoryboardViewControllerIdentifier<StartViewController> { .init(identifier: "StartViewController", storyboard: name, bundle: bundle) }
      var verificationCodeViewController: RswiftResources.StoryboardViewControllerIdentifier<VerificationCodeViewController> { .init(identifier: "VerificationCodeViewController", storyboard: name, bundle: bundle) }

      func validate() throws {
        if UIKit.UIImage(named: "Line1", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Line1' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "MenuScreen", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'MenuScreen' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Rectangle", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Rectangle' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Rectangle_big", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Rectangle_big' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Rectangle_suggested", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Rectangle_suggested' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Start", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'Start' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "airplane.arrival") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'airplane.arrival' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "airplane.departure") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'airplane.departure' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "arrow.backward") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'arrow.backward' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "arrow.backward.to.line") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'arrow.backward.to.line' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "arrow.left") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'arrow.left' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "bell") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'bell' is used in storyboard 'Main', but couldn't be loaded.") } }
        if UIKit.UIImage(named: "button", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'button' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "calendar") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'calendar' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "checkmark") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'checkmark' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "gearshape") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'gearshape' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "greaterthan") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'greaterthan' is used in storyboard 'Main', but couldn't be loaded.") } }
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "moon") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'moon' is used in storyboard 'Main', but couldn't be loaded.") } }
        if UIKit.UIImage(named: "tabler-icon-message-language", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'tabler-icon-message-language' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIColor(named: "Color", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'Color' is used in storyboard 'Main', but couldn't be loaded.") }
        if forgotPasswordViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'forgotPasswordViewController' could not be loaded from storyboard 'Main' as 'ForgotPasswordViewController'.") }
        if homeViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'homeViewController' could not be loaded from storyboard 'Main' as 'HomeViewController'.") }
        if languageViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'languageViewController' could not be loaded from storyboard 'Main' as 'LanguageViewController'.") }
        if loginViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'loginViewController' could not be loaded from storyboard 'Main' as 'LoginViewController'.") }
        if newPasswordViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'newPasswordViewController' could not be loaded from storyboard 'Main' as 'NewPasswordViewController'.") }
        if registrationViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'registrationViewController' could not be loaded from storyboard 'Main' as 'RegistrationViewController'.") }
        if settingsViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'settingsViewController' could not be loaded from storyboard 'Main' as 'SettingsViewController'.") }
        if startViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'startViewController' could not be loaded from storyboard 'Main' as 'StartViewController'.") }
        if verificationCodeViewController() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'verificationCodeViewController' could not be loaded from storyboard 'Main' as 'VerificationCodeViewController'.") }
      }
    }
  }
}